@startuml

title __CURT's Class Diagram__\n

  package Controller {
    class AuthController {
    }
  }
  

  package Controller {
    class ChoseActionController {
    }
  }
  

  package Controller {
    class ChoseActionForAccountantController {
    }
  }
  

  package Controller {
    class ChoseActionForPlayerController {
    }
  }
  

  package DB {
    class ConnectionDB {
    }
  }
  

  package Controller {
    class CreateUserController {
    }
  }
  

  package DB {
    class DB {
    }
  }
  

  package DB {
    class DeleteDB {
    }
  }
  

  package POJO {
    class Employee {
    }
  }
  

  package Controller {
    class EmployeeInfoForAccountantController {
    }
  }
  

  package Controller {
    class EmployeeInsertDialogController {
    }
  }
  

  package Controller {
    class EmployeeShowInfoController {
    }
  }
  

  package Controller {
    class EmployeeUpdateDialogController {
    }
  }
  

  package POJO {
    class Game {
    }
  }
  

  package Controller {
    class GameInsertDialogController {
    }
  }
  

  package Controller {
    class GameShowInfoController {
    }
  }
  

  package POJO {
    class GameStat {
    }
  }
  

  package Controller {
    class GameStatInsertDialogController {
    }
  }
  

  package Controller {
    class GameStatShowController {
    }
  }
  

  package Controller {
    class GameStatUpdateDialogController {
    }
  }
  

  package Controller {
    class GameUpdateDialogController {
    }
  }
  

  package Controller {
    class InfoForPlayerController {
    }
  }
  

  package DB {
    class InsertDB {
    }
  }
  

  package View {
    class MainApp {
    }
  }
  

  package POJO {
    class MyAlert {
    }
  }
  

  package POJO {
    class Player {
    }
  }
  

  package Controller {
    class PlayerInsertDialogController {
    }
  }
  

  package Controller {
    class PlayerOverviewController {
    }
  }
  

  package Controller {
    class PlayerStatInfoShowController {
    }
  }
  

  package Controller {
    class PlayerStatShowController {
    }
  }
  

  package Controller {
    class PlayerUpdateDialogController {
    }
  }
  

  package DB {
    class SelectDB {
    }
  }
  

  package DB {
    class UpdateDB {
    }
  }
  

  package POJO {
    class User {
    }
  }
  

  EmployeeInsertDialogController o-- Employee : employee
  EmployeeUpdateDialogController o-- Employee : employee
  GameInsertDialogController o-- Game : game
  GameStatInsertDialogController o-- GameStat : gameStat
  GameStatInsertDialogController o-- Game : game
  GameStatShowController o-- Game : game
  GameStatUpdateDialogController o-- GameStat : gameStat
  GameStatUpdateDialogController o-- GameStat : gameOldStat
  GameUpdateDialogController o-- Game : game
  MainApp -up-|> Application
  PlayerInsertDialogController o-- Player : player
  PlayerUpdateDialogController o-- Player : player


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
